/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Cw20HookMsg = {
  register_vesting_account: {
    address: string;
    master_address?: string | null;
    vesting_schedule: VestingSchedule;
  };
};
export type VestingSchedule = {
  linear_vesting: {
    end_time: Uint64;
    start_time: Uint64;
    vesting_amount: Uint128;
  };
} | {
  linear_vesting_with_cliff: {
    cliff_amount: Uint128;
    cliff_time: Uint64;
    end_time: Uint64;
    start_time: Uint64;
    vesting_amount: Uint128;
  };
};
export type Uint64 = string;
export type Uint128 = string;
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  register_vesting_account: {
    address: string;
    master_address?: string | null;
    vesting_schedule: VestingSchedule;
  };
} | {
  deregister_vesting_account: {
    address: string;
    denom: Denom;
    left_vesting_token_recipient?: string | null;
    vested_token_recipient?: string | null;
  };
} | {
  claim: {
    denoms: Denom[];
    recipient?: string | null;
  };
};
export type Binary = string;
export type Denom = {
  native: string;
} | {
  cw20: Addr;
};
export type Addr = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface InstantiateMsg {}
export type QueryMsg = {
  vesting_account: {
    address: string;
    limit?: number | null;
    start_after?: Denom | null;
  };
};
export interface VestingAccountResponse {
  address: string;
  vestings: VestingData[];
}
export interface VestingData {
  claimable_amount: Uint128;
  master_address?: string | null;
  vested_amount: Uint128;
  vesting_amount: Uint128;
  vesting_denom: Denom;
  vesting_schedule: VestingSchedule;
}