[package]
name = "cw3-fixed-multisig"
version = "2.0.1" # Should match contracts/core-cw3-flex-msig
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Implementing cw3 with an fixed group multisig"
license = "Apache-2.0"
repository = "https://github.com/NibiruChain/nibiru-wasm"
homepage = { workspace = true }
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw3 = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
easy-addr = { workspace = true }

[[bin]]
name = "cw3-fixed-multisig-schema"
path = "src/bin/schema.rs"